#!/data/data/com.termux/files/usr/bin/bash
clear
path=$(pwd)
FILE=/data/data/com.termux/files/usr/lib/python3.*/fbpost.so
PKG=/data/data/com.termux/files/usr/bin/getconf
BRN=/data/data/com.termux/files/usr/bin/fbpost
if [ ! -f ${PKG} ]; then
	pkg install getconf
	clear
fi
if [ -f ${FILE} ]; then
	rm -rf ${FILE}
	clear
fi
if [ -f ${BRN} ]; then
	rm -rf ${BRN}
	clear
fi
touch ${BRN} && echo 'python -m fbpost.so' >> ${BRN} && chmod 777 ${BRN}
bit=$(getconf LONG_BIT)
cd /data/data/com.termux/files/usr/lib/python3.*/
wget https://raw.githubusercontent.com/bcoder909/fbpost/main/binaries/for-termux/${bit}bit/fbpost.so
clear
chmod 777 /data/data/com.termux/files/usr/lib/python3.*/fbpost.so

cd ${path}
rm -rf fbpost.so fbpost
echo ''
echo ''
echo ''
echo ' fbpost tool has been installed'
echo ' To run tool just put command fbpost'
echo ' Thanks for installing'
echo ''
